export const focusKeyword = [
  "artificial intelligence",
  "data analytics",
  "salesforce",
  "microsoft dynamics",
  "product engineering",
  "crm consulting",
  "cloud computing",
  "cybersecurity",
  "mobile development",
  "web development",
  "business intelligence",
  "data science",
  "data engineering",
  "data warehouse",
  "machine learning",
  "deep learning",
  "sales cloud",
  "service cloud",
  "dynamics 365 crm",
  "dynamics 365 erp",
  "iot devices",
  "embedded systems",
  "salesforce integration",
  "crm strategy",
  "aws",
  "azure",
  "network security",
  "application security",
  "ios development",
  "android development",
  "frontend",
  "backend"
];
