import Footer from "@/components/site/Footer";
import Header from "@/components/site/Header";
import ReactQueryProvider from "@/provider/ReactQueryProvider";
import "@/app/globals.css"; // or wherever your global styles are

export const metadata = {
  title: "Cynoteck Technology Solutions",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <ReactQueryProvider>
      <Header />
      {children}
      <Footer />
    </ReactQueryProvider>
  );
}
